config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :users
  resources :organizations
  resources :rooms
  resources :buildings
  resources :sessions
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Default route
  get '/', to: 'home#index', as: :home
  get 'events/confirm' => 'events#confirm', as: :confirm

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building
  scope :alphabetical, -> { order('location_address') }
  scope :for_dh, -> { joins(:building).where('name LIKE ?', 'Doherty Hall') }
  scope :for_bh, -> { joins(:building).where('name LIKE ?', 'Baker Hall') }
  scope :for_ph, -> { joins(:building).where('name LIKE ?', 'Porter Hall') }
  scope :for_weh, -> { joins(:building).where('name LIKE ?', 'Wean Hall') }

  def full_name
    "#{self.building.name} #{self.location_address}"
  end

  def events_for_room
    Event.where(room_id: self.id);
  end 
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  authorize_resource

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @upcoming_events = Event.for_room(@room.id).upcoming
    @past_events = Event.for_room(@room.id).past
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:location_address, :max_capacity, :room_type, :description, :building_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location_address %>
    <%= form.text_field :location_address, id: :room_location_address %>
  </div>

  <div class="field">
    <%= form.label :max_capacity %>
    <%= form.number_field :max_capacity, id: :room_max_capacity %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :room_type %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :room_description %>
  </div>

  <div class="field">
    <%= form.label :building_id %>
    <%= form.text_field :building_id, id: :room_building_id %>
  </div>

  <div class="actions btn waves-effect waves-light">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room, :class=>"btn waves-effect waves-light" %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room Name</th>
      <th>Max capacity</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.full_name, room %></td>
        <td><%= room.max_capacity %></td>
        <td><%= room.room_type %></td>
        <% if current_user.role?(:admin) %>
          <td><%= link_to 'Edit', edit_room_path(room), :class=>"btn waves-effect waves-light" %> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path, :class=>"btn waves-effect waves-light" %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%=@room.full_name%></h1>

<p>
  <strong>Building:</strong>
  <%= link_to @room.building.name, @room.building %>
</p>

<p>
  <strong>Max capacity:</strong>
  <%= @room.max_capacity %>
</p>

<p>
  <strong>Type:</strong>
  <%= @room.room_type %>
</p>


<% if @upcoming_events.empty? %>
  <h5>This room does not have any upcoming events at the moment.</h5>
<% else %>
<h3>Upcoming Events</h3>

  <table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upcoming_events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event %></td>
        <td><%= event.date.strftime("%m/%d/%y") %></td>
        <td><%= event.start_time.strftime("%I:%M %p") %></td>
        <td><%= event.end_time.strftime("%I:%M %p") %></td>
        <td><%= event.organization.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% if @past_events.empty? %>
  <h5>This room has never been used for an event.</h5>
<% else %>
  <h3>Past Events</h3>

  <table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @past_events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event %></td>
        <td><%= event.date.strftime("%m/%d/%y") %></td>
        <td><%= event.start_time.strftime("%I:%M %p") %></td>
        <td><%= event.end_time.strftime("%I:%M %p") %></td>
        <td><%= event.organization.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<%= link_to 'Edit', edit_room_path(@room), :class=>"btn waves-effect waves-light" %>

<%= link_to 'Destroy', @room, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn waves-effect waves-light red" %>